# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f946b44eade694ba1dcd27e8b503f5ca4de9e24a944f149ad8199a893da384372772e90d5cb413fc3af734964a0db9f94ed3dcf3c4f01417a0bd0bc4860d993b

test:
  secret_key_base: 036b4e54045123a51c395bafeb94b235afddd86169482e7a4b8a2556e95983a408112a8d3f71f6a42aa12d265043d13716fe50b80a4a6f7bc5640f101debb6cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
